# File: nixpacks.toml (VERSI YANG BENAR)

# Memberitahu Nixpacks untuk menggunakan provider Python dalam format array/sequence
providers = ["python"]

# Mendefinisikan fase build
[phases.build]
cmds = ["pip install -r requirements.txt"]

# Mendefinisikan perintah start
[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app"